website:
  title: "Yanyan Zhan"
  search: true                   # allows users to search your site
  navbar:
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd       # add new files for each new page
        text: Research
      - href: about.qmd
        text: About
      - icon: github             # can add social media icons
        aria-label: GitHub


